### ISSUE TITLE
Add README 

### ISSUE THREAD

**Issue by aditya-singh9** [aditya-singh9/foodrecipe#1]
Add documentation for this repo.

**Comment by aswarthm** [comment]
Hey, I'd like to work in this. What kind of documentation are you expecting?
I thought of adding a GitHub Pages link, anything else you would like me to include?

**Comment by aditya-singh9** [comment]
See my other repos and see the way i have written the documentation.
I think i will go with that format only.

If you want to work on adding documentation then let me know in comments, i will assign it to you

**Comment by aswarthm** [comment]
Yeah sure, thanks
