### ISSUE TITLE
landing section

### ISSUE THREAD

**Issue by leesha19** [aditya-singh9/foodrecipe#18]
hey there @aditya-singh9 , I WOULD LIKE TO IMPROVE THIS SECTION AS IT IS NOT LOOKING ATTRACTIVE 
we can change the background plus hover effect on the button #25 
<img width="1280" alt="Screenshot 2022-10-01 at 1 00 13 PM" src="https://user-images.githubusercontent.com/88451246/193398375-0b639f90-88e9-4cde-be22-6c1db39f81f8.png">

**Comment by leesha19** [comment]
can i change the background image

**Comment by aditya-singh9** [comment]
To what?
Send the image you want to change to

**Comment by leesha19** [comment]
> To what? Send the image you want to change to

![pexels-pixabay-326279 (1)](https://user-images.githubusercontent.com/88451246/193412087-b63c13e7-cc46-459d-b169-c78eef274764.jpg)

**Comment by leesha19** [comment]
> To what? Send the image you want to change to

is it alright coz its looking better than that

**Comment by aditya-singh9** [comment]
Okay you can add

**Comment by leesha19** [comment]
> Okay you can add

you can close this issue as pull request 25 is merged
