### ISSUE TITLE
adding actual text to the paragraphs (4)

### ISSUE THREAD

**Issue by dreymotoh** [aditya-singh9/foodrecipe#26]
to the 3 sections under the main (get inspired, get rewarded, get social) and the introducing the fudi app paragraph

**Comment by dreymotoh** [comment]
great! thanks :) can you tell me what fudi is about? for the introducing the fudi paragraph

**Comment by dreymotoh** [comment]
hi! i added changes to the index.html file with the (p elements) that have (h2) elements

**Comment by dreymotoh** [comment]
sorry for creating a new branch, i messed up there :///

**Comment by aditya-singh9** [comment]
I do not think what these changes are valid for hacktoberfest
 Please make quality prs else i will mark it invalid or spam

**Comment by dreymotoh** [comment]
ok! what would you like the paragraphs to include then ?
