### ISSUE TITLE
Add Hover Animations to Browse by cuisine section

### ISSUE THREAD

**Issue by navya-Singla-1-3-0-9** [aditya-singh9/foodrecipe#37]
I would like to contribute to this issue. Please assign this to me.

**Comment by aditya-singh9** [comment]
https://github.com/aditya-singh9/foodrecipe/issues/12

**Comment by aditya-singh9** [comment]
You are creating multiple duplicate issues. 
That seems spam to me

**Comment by navya-Singla-1-3-0-9** [comment]
Hey sorry, I didn't notice that a similar issue has been created:(. Could you please remove the spam tag as I don't wish to get disqualified. This is my first time contributing to open source!

**Comment by aditya-singh9** [comment]
I will remove only one spam label.
And when making further contributions remember to check the opened issues.

**Comment by navya-Singla-1-3-0-9** [comment]
Sure, thanks!
