### ISSUE TITLE
Contributors.md file missing

### ISSUE THREAD

**Issue by dhruvbhatia1** [aditya-singh9/foodrecipe#5]
Would like to create and add the contributors.md file in the repo. Kindly assign it to me.

**Comment by georgioupanayiotis** [comment]
@dhruvbhatia1  can you please assign this to me?

**Comment by dhruvbhatia1** [comment]
@georgioupanayiotis I am already working on this issue. 
Please feel free to create a new different issue and the project maintainer will assign it to you.
