### ISSUE TITLE
fixing ui 

### ISSUE THREAD

**Issue by leesha19** [aditya-singh9/foodrecipe#57]
i think something happened wrong can i fix this 

<img width="1280" alt="Screenshot 2022-10-07 at 2 46 52 PM" src="https://user-images.githubusercontent.com/88451246/194519315-7c71dfe4-c6eb-4323-b8dc-4ed9bbe53b4b.png">

**Comment by leesha19** [comment]
@aditya-singh9 do you need dark mode for the website or else i should remove the button

**Comment by aditya-singh9** [comment]
After giving it some thought, i think we should remove the theme stuff.

**Comment by leesha19** [comment]
> After giving it some thought, i think we should remove the theme stuff.

we should keep it simple
