### ISSUE TITLE
Add social media icons in footer.

### ISSUE THREAD

**Issue by dhruvbhatia1** [aditya-singh9/foodrecipe#6]
Would like to add social media icons in footers. 
Will make the footer look better visually too.

Please assign this issue to me.

**Comment by heza-ru** [comment]
I would like to work on this.

**Comment by RahulSankhla312** [comment]
hey @dhruvbhatia1  could you assign this issue to me .

**Comment by aditya-singh9** [comment]
> hey @dhruvbhatia1  could you assign this issue to me .
> 

This one is already assigned to @dhruvbhatia1 .
