### ISSUE TITLE
Adding Links to the social media apps in the footer

### ISSUE THREAD

**Issue by itzwow** [aditya-singh9/foodrecipe#61]
The Social media links are not embedded in the footer.

I would like to work on this issue.

**Comment by aditya-singh9** [comment]
What links will you add?

**Comment by itzwow** [comment]
> What links will you add?

If you have site specific pages or social media handles then I can add those links else as of now I will add the default login links of these social media handles

**Comment by mrinalstark** [comment]
I have added login site of the apps given in the Footer

**Comment by aditya-singh9** [comment]
I think i will let this issue go
As just adding links means you havent made qualitg contribution
