### ISSUE TITLE
Add download buttons.

### ISSUE THREAD

**Issue by dhruvbhatia1** [aditya-singh9/foodrecipe#7]
Will all download buttons in the 'Fudi App' section. 

The buttons will look something like this -
<img width="133" alt="image" src="https://user-images.githubusercontent.com/65610188/193246518-caf20b2c-8701-43f6-bf6e-cfc762554758.png">

<img width="140" alt="image" src="https://user-images.githubusercontent.com/65610188/193246647-a412a102-51f8-4518-acb0-67e1d0a3d009.png">

**Comment by appledora** [comment]
hi @dhruvbhatia1 , I think I could take this up. Would you assign me this, kindly?

**Comment by dhruvbhatia1** [comment]
hi @appledora, I am currently working on this issue. 
Please feel free to create new issues and the project maintainer will assign it to you.
