### ISSUE TITLE
Adding about us section 

### ISSUE THREAD

**Issue by wizeewig** [aditya-singh9/foodrecipe#9]

**Comment by wizeewig** [comment]
@aditya-singh9 I would like to add a about us page. May I?

**Comment by Nincompup** [comment]
@aditya-singh9  I would like to work on this issue. May I?

**Comment by Abhishekvermaa** [comment]
I would like to contribute in this isuue if someone is not working.

**Comment by wizeewig** [comment]
I am working on it
